### ISSUE TITLE
power-outage scenario container image exits prematurely 

### ISSUE THREAD

**Issue by mallilinux1980** [krkn-chaos/krkn-hub#193]
container exits prematurely due to KUBECONFIG not set properly inside a container. But when i run container in /bin/bash i can see KUBECONFIG mounted under /root/.kube/config and not sure why unset KUBECONFIG is run as per logs below.

.
$ podman run -it --rm --name=power --net=host --env-host=true -v /tmp/kubeconfig-42:/root/.kube/config:Z quay.io/krkn-chaos/krkn-hub:power-outages 
+ source /root/main_env.sh
++ export CERBERUS_ENABLED=False
++ CERBERUS_ENABLED=False
++ export CERBERUS_URL=http://0.0.0.0:8080
++ CERBERUS_URL=http://0.0.0.0:8080
++ export KRKN_KUBE_CONFIG=/root/.kube/config
++ KRKN_KUBE_CONFIG=/root/.kube/config
++ export WAIT_DURATION=60
++ WAIT_DURATION=60
++ export ITERATIONS=1
++ ITERATIONS=1
++ export DAEMON_MODE=False
++ DAEMON_MODE=False
++ export RETRY_WAIT=120
++ RETRY_WAIT=120
++ export PUBLISH_KRAKEN_STATUS=False
++ PUBLISH_KRAKEN_STATUS=False
++ export SIGNAL_ADDRESS=0.0.0.0
++ SIGNAL_ADDRESS=0.0.0.0
++ export PORT=8081
++ PORT=8081
++ export SIGNAL_STATE=RUN
++ SIGNAL_STATE=RUN
++ export DEPLOY_DASHBOARDS=False
++ DEPLOY_DASHBOARDS=False
++ export CAPTURE_METRICS=False
++ CAPTURE_METRICS=False
++ export ENABLE_ALERTS=False
++ ENABLE_ALERTS=False
++ export ALERTS_PATH=config/alerts
++ ALERTS_PATH=config/alerts
++ export ES_SERVER=http://0.0.0.0:9200
++ ES_SERVER=http://0.0.0.0:9200
++ export CHECK_CRITICAL_ALERTS=False
++ CHECK_CRITICAL_ALERTS=False
++ export KUBE_BURNER_URL=https://github.com/cloud-bulldozer/kube-burner/releases/download/v1.7.0/kube-burner-1.7.0-Linux-x86_64.tar.gz
++ KUBE_BURNER_URL=https://github.com/cloud-bulldozer/kube-burner/releases/download/v1.7.0/kube-burner-1.7.0-Linux-x86_64.tar.gz
++ export TELEMETRY_ENABLED=False
++ TELEMETRY_ENABLED=False
++ export TELEMETRY_API_URL=https://ulnmf9xv7j.execute-api.us-west-2.amazonaws.com/production
++ TELEMETRY_API_URL=https://ulnmf9xv7j.execute-api.us-west-2.amazonaws.com/production
++ export TELEMETRY_USERNAME=redhat-chaos
++ TELEMETRY_USERNAME=redhat-chaos
++ export TELEMETRY_PASSWORD=
++ TELEMETRY_PASSWORD=
++ export TELEMETRY_PROMETHEUS_BACKUP=True
++ TELEMETRY_PROMETHEUS_BACKUP=True
++ export TELEMTRY_FULL_PROMETHEUS_BACKUP=False
++ TELEMTRY_FULL_PROMETHEUS_BACKUP=False
++ export TELEMETRY_BACKUP_THREADS=5
++ TELEMETRY_BACKUP_THREADS=5
++ export TELEMETRY_ARCHIVE_PATH=/tmp
++ TELEMETRY_ARCHIVE_PATH=/tmp
++ export TELEMETRY_MAX_RETRIES=0
++ TELEMETRY_MAX_RETRIES=0
++ export TELEMETRY_RUN_TAG=chaos
++ TELEMETRY_RUN_TAG=chaos
++ export TELEMETRY_ARCHIVE_SIZE=1000
++ TELEMETRY_ARCHIVE_SIZE=1000
++ export TELEMETRY_LOGS_BACKUP=False
++ TELEMETRY_LOGS_BACKUP=False
++ export 'TELEMETRY_FILTER_PATTERN=["(\\w{3}\\s\\d{1,2}\\s\\d{2}:\\d{2}:\\d{2}\\.\\d+).+","kinit (\\d+/\\d+/\\d+\\s\\d{2}:\\d{2}:\\d{2})\\s+","(\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d+Z).+"]'
++ TELEMETRY_FILTER_PATTERN='["(\\w{3}\\s\\d{1,2}\\s\\d{2}:\\d{2}:\\d{2}\\.\\d+).+","kinit (\\d+/\\d+/\\d+\\s\\d{2}:\\d{2}:\\d{2})\\s+","(\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d+Z).+"]'
++ export TELEMETRY_CLI_PATH=
++ TELEMETRY_CLI_PATH=
++ export TELEMETRY_EVENTS_BACKUP=True
++ TELEMETRY_EVENTS_BACKUP=True
**++ unset KUBECONFIG**
+ source /root/env.sh
++ export SHUTDOWN_DURATION=1200
++ SHUTDOWN_DURATION=1200
++ export CLOUD_TYPE=aws
++ CLOUD_TYPE=aws
++ export TIMEOUT=180
++ TIMEOUT=180
++ export SCENARIO_TYPE=cluster_shut_down_scenarios
++ SCENARIO_TYPE=cluster_shut_down_scenarios
++ export 'SCENARIO_FILE=- scenarios/cluster_shut_down_scenario.yml'
++ SCENARIO_FILE='- scenarios/cluster_shut_down_scenario.yml'
++ export SCENARIO_POST_ACTION=
++ SCENARIO_POST_ACTION=
+ source /root/common_run.sh
+ config_setup
+ envsubst
+ checks
+ check_oc
+ log 'Checking if OpenShift client is installed'
++ date +%d-%m-%YT%H:%M:%S
+ echo -e '\033[1m10-07-2024T02:45:06 Checking if OpenShift client is installed\033[0m'
10-07-2024T02:45:06 Checking if OpenShift client is installed
+ which oc
+ alias
+ eval declare -f
++ declare -f
+ /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot oc
/usr/local/bin/oc
+ check_kubectl
+ log 'Checking if kubernetes client is installed'
++ date +%d-%m-%YT%H:%M:%S
+ echo -e '\033[1m10-07-2024T02:45:06 Checking if kubernetes client is installed\033[0m'
10-07-2024T02:45:06 Checking if kubernetes client is installed
+ which kubectl
+ alias
+ eval declare -f
++ declare -f
+ /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot kubectl
/usr/local/bin/kubectl
+ check_cluster_version
+ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"33a7a8bcccdd1c7c0e2f51609d832d31232d2f26", GitTreeState:"clean", BuildDate:"2023-12-13T22:07:37Z", GoVersion:"go1.20.10 X:strictfipsruntime", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Unable to connect to the server: EOF
+ log 'Unable to connect to the cluster, please check if it'\''s up and make sure the KUBECONFIG is set correctly'
++ date +%d-%m-%YT%H:%M:%S
+ echo -e '\033[1m10-07-2024T02:45:17 Unable to connect to the cluster, please check if it'\''s up and make sure the KUBECONFIG is set correctly\033[0m'
10-07-2024T02:45:17 Unable to connect to the cluster, please check if it's up and make sure the KUBECONFIG is set correctly
+ exit 1

**Comment by tsebastiani** [comment]
Hi @mallilinux1980 sorry for the late response.
As I can see from the command that you issued there's a problem in the path where you mount the kubeconfig, since the latest release we changed the containers to work on unprivileged mode, so the path where you mount the kubeconfig (as you can see from the [Documentation](https://github.com/krkn-chaos/krkn-hub/blob/main/docs/power-outages.md)) you have to mount the kubeconfig in `/home/krkn/.kube/config:Z` instead of `/root/.kube/config`.
