### ISSUE TITLE
node-scenarios: several enhancements

### ISSUE THREAD

**Issue by ebattat** [krkn-chaos/krkn-hub#223]
1. Add Duration to ElasticSearch: duration
2. Add Note time till ready: node_ready_time
3. Fix 2024-11-06 04:02:44,865 [ERROR] 'namespace'

**Comment by paigerube14** [comment]
Hello, thanks for opening this issue(s). I believe the code for these changes will actually need to go into the lowest level of our code base (krkn-lib). would you be able to create an issue there and link the two! Thanks for the ideas/contributions

**Comment by ebattat** [comment]
Open issue under  [(krkn-lib) ](https://github.com/krkn-chaos/krkn-lib/issues/135)
